### ISSUE TITLE
Error "AutoHotkeyUX.ahk" is missing!

### ISSUE THREAD

**Issue by naxl** [AutoHotkey/AutoHotkeyUX#12]
when i first installed AHK v2.0.4 it was working fine, and there used to be two EXEs running AutoHotkey.exe from UX subdirectory and AutoHotkye64.exe Unicode but when I accidently uninstalled the version v2 the version v1.1.37 stayed and I reinstalled v2 to find me not able to start the AutoHotkey.exe from UX folder it raises AutoHotkeyUX.ahk missing error! Please Help, I am new to AHK!!

**Comment by naxl** [comment]
I have tried reinstalling multiple times but no luck! v2 seems to not work fine as my motto of bringing an Executable to focus doesn't seem to work!

**Comment by Lexikos** [comment]
There is no "AutoHotkey.exe" in the UX folder. There is "AutoHotkeyUX.exe", and you are not supposed to run it directly. If you still do not know how to use the program, I would suggest checking some of the links under [Next Steps](https://www.autohotkey.com/docs/v2/howto/Install.htm#Next_Steps).

This issue tracker is for actual issues with the UX scripts, not for this type of request, and it is not monitored closely or by many people. If you still have issue after reading some tutorials, I would suggest posting in the [Ask for Help](https://www.autohotkey.com/boards/viewforum.php?f=82) forum.
